Layout/LineLength:
  Max: 140

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 19

Metrics/AbcSize:
  Max: 43

Naming/MethodParameterName:
  Enabled: false

Lint/RaiseException:
  Enabled: true
  
Lint/StructNewOverride:
  Enabled: true
  
Style/HashEachMethods:
  Enabled: true
  
Style/HashTransformKeys:
  Enabled: true
  
Style/HashTransformValues:
  Enabled: true